In [1]:
import numpy as np
import pandas as pd
import string

In [2]:
movies = pd.read_csv('dataset/tmdb_5000_movies.csv')
credits = pd.read_csv('dataset/tmdb_5000_credits.csv')

In [3]:
movies = movies.merge(credits, on='title')

In [4]:
movies.head(1)
# credits.head(1)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."

In [5]:
# genres
# id
# keywords
# title
# overview
# cast
# crew

movies = movies[['movie_id', 'title', 'overview', 'genres', 'keywords', 'cast', 'crew']]

In [6]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4809 entries, 0 to 4808
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4809 non-null   int64
 1   title     4809 non-null   object
 2   overview  4806 non-null   object
 3   genres    4809 non-null   object
 4   keywords  4809 non-null   object
 5   cast      4809 non-null   object
 6   crew      4809 non-null   object
dtypes: int64(1), object(6)
memory usage: 300.6+ KB

In [7]:
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [8]:
movies.dropna(inplace=True)

In [9]:
movies.duplicated().sum()

0

In [10]:
movies.iloc[0].genres

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [11]:
import ast
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i["name"])
    return L

def convert3(obj):
    L = []
    count = 0
    for i in ast.literal_eval(obj):
        if count < 3:
            L.append(i["name"])
            count += 1
        else:
            break
    return L

def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i["job"] == "Director":
            L.append(i["name"])
            break
    return L

In [12]:
movies["genres"] = movies["genres"].apply(convert)

In [13]:
movies["keywords"] = movies["keywords"].apply(convert)

In [14]:
movies["cast"] = movies["cast"].apply(convert3)

In [15]:
movies["crew"] = movies["crew"].apply(fetch_director)

In [16]:
movies['overview'] = movies['overview'].apply(lambda x: x.split())

In [17]:
movies['genres'] = movies['genres'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['cast'] = movies['cast'].apply(lambda x: [i.replace(" ", "") for i in x])
movies['crew'] = movies['crew'].apply(lambda x: [i.replace(" ", "") for i in x])

In [18]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [19]:
movies["tags"] = movies["overview"] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

In [20]:
new_df = movies[['movie_id', 'title', 'tags']]
new_df.head()

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."

In [21]:
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

C:\Users\SHUBHA~1\AppData\Local\Temp/ipykernel_19108/1824047427.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [22]:
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())
new_df

C:\Users\SHUBHA~1\AppData\Local\Temp/ipykernel_19108/3865390039.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couple's honeymoon is upended by th...
4806,231617,"Signed, Sealed, Delivered","""signed, sealed, delivered"" introduces a dedic..."
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [23]:
translator = str.maketrans("", "", string.punctuation)
new_df['tags'] = new_df['tags'].apply(lambda x: x.translate(translator))
new_df

C:\Users\SHUBHA~1\AppData\Local\Temp/ipykernel_19108/4002957523.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: x.translate(translator))

,movie_id,title,tags
0,19995,Avatar,in the 22nd century a paraplegic marine is dis...
1,285,Pirates of the Caribbean: At World's End,captain barbossa long believed to be dead has ...
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,john carter is a warweary former military capt...
...,...,...,...
4804,9367,El Mariachi,el mariachi just wants to play his guitar and ...
4805,72766,Newlyweds,a newlywed couples honeymoon is upended by the...
4806,231617,"Signed, Sealed, Delivered",signed sealed delivered introduces a dedicated...
4807,126186,Shanghai Calling,when ambitious new york attorney sam is sent t...
4808,25975,My Date with Drew,ever since the second grade when he first saw ...

In [24]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [25]:
def stem(text):
    y = []
    
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [26]:
new_df['tags'] = new_df['tags'].apply(stem)
new_df['tags']

C:\Users\SHUBHA~1\AppData\Local\Temp/ipykernel_19108/4269356531.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

0       in the 22nd centuri a parapleg marin is dispat...
1       captain barbossa long believ to be dead ha com...
2       a cryptic messag from bondâ€™ past send him on a...
3       follow the death of district attorney harvey d...
4       john carter is a warweari former militari capt...
                              ...
4804    el mariachi just want to play hi guitar and ca...
4805    a newlyw coupl honeymoon is upend by the arriv...
4806    sign seal deliv introduc a dedic quartet of ci...
4807    when ambiti new york attorney sam is sent to s...
4808    ever sinc the second grade when he first saw h...
Name: tags, Length: 4806, dtype: object

In [48]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

In [49]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [51]:
cv.get_feature_names_out()

array(['007', '10', '100', ..., 'zone', 'zoo', 'zooeydeschanel'],
      dtype=object)

In [52]:
from sklearn.metrics.pairwise import cosine_similarity

In [53]:
similarity = cosine_similarity(vectors)
similarity[0]

array([1.        , 0.0836242 , 0.08492078, ..., 0.06419407, 0.02360961,
       0.        ])

In [45]:
sorted(list(enumerate(similarity[0])), reverse=True, key=lambda x: x[1])

[(0, 1.0000000000000002),
 (2409, 0.26257545381445874),
 (539, 0.24715576637149034),
 (507, 0.24403555043462524),
 (1216, 0.24037008503093257),
 (1204, 0.23870495801314426),
 (260, 0.23007892341722033),
 (61, 0.22880215766121476),
 (1194, 0.22880215766121476),
 (778, 0.22875450543583872),
 (1920, 0.21977383072747692),
 (2786, 0.21182963643408081),
 (2999, 0.20965696734438366),
 (322, 0.20780973338645242),
 (466, 0.20483662259967567),
 (973, 0.20464687117164013),
 (83, 0.20380986614602725),
 (972, 0.2013190579900678),
 (151, 0.20033416898825337),
 (172, 0.20033416898825335),
 (3730, 0.2001601922563589),
 (2204, 0.20006252931214213),
 (1831, 0.19985201625794738),
 (1089, 0.19944037418082106),
 (3608, 0.19861453057473932),
 (74, 0.19795764159656265),
 (582, 0.19795764159656265),
 (4192, 0.19611613513818407),
 (2333, 0.19611613513818402),
 (301, 0.19571218798399537),
 (300, 0.19535451620220173),
 (1444, 0.19418390934515434),
 (47, 0.19277164398874672),
 (3675, 0.19096396641051544),
 (4048, 0.19003715589632164),
 (1329, 0.18842228790639834),
 (495, 0.1884222879063983),
 (942, 0.18685673434682065),
 (4405, 0.18490006540840973),
 (1201, 0.1849000654084097),
 (577, 0.18427434427242975),
 (2971, 0.18248296715045295),
 (305, 0.1815682598006407),
 (1275, 0.1815682598006407),
 (4, 0.18116432546313532),
 (27, 0.18014417303072303),
 (41, 0.17937941173234997),
 (3327, 0.17902871850985821),
 (94, 0.17841031003501576),
 (1056, 0.17722938923964168),
 (220, 0.1754116038614058),
 (1321, 0.17471413945365305),
 (168, 0.17295817388759027),
 (4230, 0.17093520167692652),
 (184, 0.1709352016769265),
 (3538, 0.16898159235484367),
 (46, 0.16724840200141816),
 (91, 0.16724840200141816),
 (3999, 0.16724840200141816),
 (4336, 0.16709347060920102),
 (373, 0.16694514082354447),
 (1071, 0.16526725762745997),
 (931, 0.16477051091432687),
 (1982, 0.16477051091432687),
 (67, 0.16239958858823),
 (7, 0.1617875572323585),
 (3162, 0.15889162445979146),
 (595, 0.1585187847802434),
 (1537, 0.1585187847802434),
 (1178, 0.15794943794779692),
 (342, 0.15724272550828775),
 (483, 0.15701857325533194),
 (108, 0.15695698526580623),
 (1808, 0.15585730003983933),
 (2731, 0.15408338784034142),
 (529, 0.1539670545751043),
 (777, 0.1539670545751043),
 (149, 0.15202972471705734),
 (1965, 0.15202972471705734),
 (311, 0.15191090506255),
 (2686, 0.15191090506255),
 (31, 0.1513068831672006),
 (1327, 0.1513068831672006),
 (2515, 0.1513068831672006),
 (1383, 0.1500468969841066),
 (36, 0.14978617237881955),
 (740, 0.14846644469434814),
 (111, 0.14824986333222023),
 (127, 0.146943671674129),
 (26, 0.1465158871516513),
 (52, 0.1465158871516513),
 (187, 0.14484136487558028),
 (513, 0.14484136487558028),
 (1344, 0.14484136487558028),
 (275, 0.1437993271357627),
 (294, 0.1437993271357627),
 (579, 0.1437993271357627),
 (2075, 0.1437993271357627),
 (661, 0.14351616441832768),
 (1273, 0.1432229748078866),
 (1355, 0.1432229748078866),
 (2133, 0.14235407108686474),
 (838, 0.142336136715633),
 (3354, 0.14153462926807447),
 (1301, 0.14153462926807445),
 (1479, 0.14121975762272054),
 (2760, 0.14121975762272052),
 (2284, 0.1401425507601155),
 (1396, 0.14011213457945124),
 (668, 0.13977131156292244),
 (332, 0.13937366833451514),
 (581, 0.13937366833451514),
 (17, 0.13797289239745258),
 (72, 0.1373087590952724),
 (461, 0.1373087590952724),
 (1945, 0.1373087590952724),
 (56, 0.13655774839978377),
 (490, 0.13655774839978377),
 (1488, 0.13655774839978377),
 (1774, 0.13655774839978377),
 (1938, 0.1358732440973515),
 (3443, 0.1358732440973515),
 (413, 0.13533299049019168),
 (859, 0.13533299049019168),
 (2169, 0.13533299049019168),
 (2496, 0.13533299049019168),
 (95, 0.1345345587992625),
 (505, 0.13355611265883557),
 (935, 0.13355611265883557),
 (3781, 0.13355611265883557),
 (568, 0.13344012817090595),
 (1560, 0.13344012817090595),
 (2480, 0.13323467750529824),
 (4348, 0.13323467750529824),
 (4353, 0.13323467750529824),
 (502, 0.1319717610643751),
 (126, 0.1316245316231641),
 (843, 0.1316245316231641),
 (4079, 0.1316245316231641),
 (150, 0.13119107973822086),
 (249, 0.1307440900921227),
 (2584, 0.1307440900921227),
 (3982, 0.1307440900921227),
 (4018, 0.1307440900921227),
 (1015, 0.12988108336653278),
 (1086, 0.12988108336653278),
 (3409, 0.12988108336653278),
 (158, 0.12955005512625914),
 (18, 0.12857571271486287),
 (2789, 0.1283881477532739),
 (3622, 0.1282051282051282),
 (134, 0.12810252304406972),
 (1004, 0.12810252304406972),
 (1096, 0.12810252304406972),
 (1373, 0.12810252304406972),
 (3093, 0.12725695259515554),
 (14, 0.12659242088545833),
 (2450, 0.12659242088545833),
 (2938, 0.12659242088545833),
 (2873, 0.126155140059354),
 (368, 0.12561485860426555),
 (476, 0.12561485860426555),
 (2378, 0.12561485860426555),
 (4490, 0.12561485860426555),
 (5, 0.12503908082008883),
 (1878, 0.12403473458920845),
 (3218, 0.12403473458920844),
 (754, 0.1235415527768502),
 (1297, 0.1235415527768502),
 (1823, 0.1235415527768502),
 (2181, 0.1235415527768502),
 (773, 0.12326671027227314),
 (1158, 0.12326671027227314),
 (2970, 0.12326671027227314),
 (102, 0.12201777521731262),
 (1741, 0.12201777521731262),
 (1322, 0.1215783580010781),
 (208, 0.12104550653376048),
 (487, 0.12104550653376048),
 (1658, 0.12104550653376048),
 (2620, 0.12104550653376048),
 (1455, 0.12104550653376046),
 (138, 0.1207011373963169),
 (438, 0.1207011373963169),
 (1037, 0.1207011373963169),
 (541, 0.12009611535381534),
 (3083, 0.12009611535381534),
 (4538, 0.12009611535381534),
 (549, 0.11935247900657214),
 (1497, 0.11916871834484359),
 (68, 0.11894020669001051),
 (781, 0.11894020669001051),
 (2652, 0.11894020669001051),
 (139, 0.1182624791978165),
 (166, 0.1180480411624714),
 (182, 0.1180480411624714),
 (870, 0.1180480411624714),
 (937, 0.1180480411624714),
 (422, 0.11694106924093722),
 (1047, 0.11694106924093722),
 (3376, 0.11694106924093722),
 (278, 0.11678545896676293),
 (432, 0.11678545896676293),
 (900, 0.11678545896676293),
 (1299, 0.11678545896676293),
 (1446, 0.11678545896676293),
 (3235, 0.11678545896676293),
 (189, 0.11651034560709261),
 (1673, 0.11651034560709261),
 (1715, 0.11651034560709261),
 (2674, 0.11651034560709261),
 (4568, 0.11651034560709261),
 (589, 0.11566298639324803),
 (1617, 0.11556254088025608),
 (28, 0.11503946170861017),
 (122, 0.11503946170861017),
 (449, 0.11503946170861017),
 (1274, 0.11503946170861017),
 (2741, 0.11503946170861017),
 (4673, 0.11503946170861017),
 (2701, 0.11437725271791938),
 (1002, 0.11322770341445959),
 (1942, 0.11322770341445959),
 (3721, 0.11322770341445959),
 (160, 0.11322770341445958),
 (1220, 0.11322770341445958),
 (236, 0.11322770341445956),
 (2060, 0.11322770341445956),
 (536, 0.11211213233271874),
 (1418, 0.11211213233271873),
 (1616, 0.11149893466761211),
 (2372, 0.11102889792108188),
 (3147, 0.11094003924504581),
 (307, 0.1104452707417832),
 (889, 0.1104452707417832),
 (1348, 0.11020775375559674),
 (1745, 0.11020775375559674),
 (1512, 0.10997646755364593),
 (123, 0.10997646755364592),
 (85, 0.10991300127873237),
 (87, 0.10984700727621793),
 (232, 0.10984700727621793),
 (678, 0.10984700727621793),
 (454, 0.10895340841010223),
 (3309, 0.10895340841010223),
 (230, 0.10878565864408421),
 (21, 0.10826639239215334),
 (50, 0.10826639239215334),
 (786, 0.10826639239215334),
 (2583, 0.10826639239215334),
 (2868, 0.10826639239215334),
 (4468, 0.10826639239215334),
 (81, 0.108094949066235),
 (228, 0.10795837927188262),
 (279, 0.10795837927188262),
 (3630, 0.10795837927188262),
 (1574, 0.10741723110591493),
 (200, 0.10741723110591492),
 (653, 0.10741723110591492),
 (808, 0.10741723110591492),
 (4135, 0.10741723110591492),
 (692, 0.10699012312772824),
 (2498, 0.10699012312772824),
 (2547, 0.10699012312772824),
 (330, 0.10675210253672475),
 (814, 0.10675210253672475),
 (1031, 0.10675210253672475),
 (939, 0.1060991783534611),
 (262, 0.10604746049596296),
 (420, 0.10604746049596296),
 (3212, 0.10595570407774764),
 (1747, 0.10529962529853128),
 (2072, 0.10529962529853128),
 (3498, 0.10529962529853128),
 (572, 0.105129283382795),
 (229, 0.10482848367219183),
 (238, 0.10482848367219183),
 (256, 0.10482848367219183),
 (1524, 0.10482848367219183),
 (1575, 0.10482848367219183),
 (2456, 0.10482848367219183),
 (2634, 0.10482848367219183),
 (3055, 0.10482848367219183),
 (170, 0.10423454980627081),
 (131, 0.10390486669322622),
 (1082, 0.10390486669322622),
 (1833, 0.10390486669322622),
 (2817, 0.10390486669322622),
 (3008, 0.10390486669322622),
 (3340, 0.10390486669322622),
 (4626, 0.10390486669322622),
 (2099, 0.10360237735649558),
 (467, 0.10336227882434038),
 (1277, 0.10336227882434038),
 (1496, 0.10336227882434038),
 (295, 0.10256410256410256),
 (854, 0.10256410256410256),
 (1195, 0.10256410256410256),
 (1237, 0.10256410256410256),
 (3881, 0.1025115460130912),
 (105, 0.10241831129983783),
 (624, 0.10241831129983783),
 (1166, 0.10241831129983783),
 (1501, 0.10241831129983783),
 (2161, 0.10241831129983783),
 (2323, 0.10241831129983783),
 (2521, 0.10241831129983783),
 (3954, 0.10241831129983783),
 (4623, 0.10241831129983783),
 (84, 0.10168147934776052),
 (403, 0.10168147934776052),
 (2439, 0.10168147934776052),
 (10, 0.10127393670836667),
 (174, 0.10127393670836667),
 (369, 0.10127393670836667),
 (3102, 0.10127393670836667),
 (3152, 0.10127393670836667),
 (3628, 0.10127393670836667),
 (3634, 0.10127393670836667),
 (3720, 0.10127393670836667),
 (3874, 0.10127393670836667),
 (3441, 0.10087125544480038),
 (627, 0.10016708449412667),
 (1860, 0.10016708449412667),
 (2053, 0.10016708449412667),
 (3621, 0.10016708449412667),
 (4638, 0.10016708449412667),
 (48, 0.10008009612817946),
 (70, 0.10003126465607107),
 (75, 0.10003126465607107),
 (312, 0.10003126465607107),
 (472, 0.10003126465607107),
 (2247, 0.10003126465607107),
 (3428, 0.10003126465607107),
 (4045, 0.10003126465607107),
 (654, 0.09930726528736966),
 (223, 0.09883324222148016),
 (2035, 0.09883324222148016),
 (2148, 0.09883324222148016),
 (3755, 0.09883324222148016),
 (1439, 0.09855206599818042),
 (157, 0.09805806756909202),
 (263, 0.09805806756909202),
 (1077, 0.09805806756909202),
 (1280, 0.09805806756909202),
 (2259, 0.09805806756909202),
 (2762, 0.09805806756909202),
 (2787, 0.09805806756909202),
 (4331, 0.09805806756909202),
 (45, 0.09781383788084239),
 (510, 0.09767725810110087),
 (687, 0.09767725810110087),
 (988, 0.09767725810110087),
 (1294, 0.09767725810110087),
 (1614, 0.09767725810110087),
 (2013, 0.09767725810110087),
 (3935, 0.09767725810110087),
 (1639, 0.09709195467257717),
 (334, 0.09656090991705352),
 (535, 0.09656090991705352),
 (587, 0.09656090991705352),
 (898, 0.09656090991705352),
 (1401, 0.09656090991705352),
 (2253, 0.09656090991705352),
 (4777, 0.09656090991705352),
 (1405, 0.09638582199437336),
 (1775, 0.09638582199437336),
 (233, 0.09607689228305229),
 (319, 0.09607689228305229),
 (660, 0.09607689228305229),
 (878, 0.09607689228305229),
 (1156, 0.09607689228305229),
 (1378, 0.09607689228305229),
 (1686, 0.09607689228305229),
 (2645, 0.09607689228305229),
 (3663, 0.09607689228305229),
 (643, 0.09548198320525772),
 (908, 0.09548198320525772),
 (2241, 0.09548198320525772),
 (3701, 0.09548198320525772),
 (3783, 0.09548198320525772),
 (363, 0.09501857794816083),
 (491, 0.09501857794816083),
 (206, 0.09466737492152845),
 (9, 0.09443843292997713),
 (410, 0.09443843292997713),
 (480, 0.09443843292997713),
 (1109, 0.09443843292997713),
 (1523, 0.09443843292997713),
 (1771, 0.09443843292997713),
 (4545, 0.09435641951204965),
 (33, 0.09421114395319916),
 (362, 0.09421114395319916),
 (791, 0.09421114395319916),
 (1573, 0.09421114395319916),
 (1721, 0.09421114395319916),
 (4198, 0.09421114395319916),
 (4203, 0.09421114395319916),
 (4256, 0.09421114395319916),
 (4472, 0.09421114395319916),
 (371, 0.09342836717341034),
 (445, 0.09342836717341034),
 (2852, 0.09342836717341034),
 (813, 0.09245003270420486),
 (1701, 0.09245003270420486),
 (1846, 0.09245003270420486),
 (2713, 0.09245003270420486),
 (2820, 0.09245003270420486),
 (3464, 0.09245003270420486),
 (3620, 0.09245003270420486),
 (4010, 0.09245003270420486),
 (148, 0.09245003270420485),
 (244, 0.09245003270420485),
 (325, 0.09245003270420485),
 (920, 0.09245003270420485),
 (1727, 0.09245003270420485),
 (1884, 0.09245003270420485),
 (2396, 0.09245003270420485),
 (4403, 0.09245003270420485),
 (2190, 0.09183979479633063),
 (43, 0.0915018021743355),
 (302, 0.0915018021743355),
 (2488, 0.0915018021743355),
 (2650, 0.0915018021743355),
 (3389, 0.0915018021743355),
 (799, 0.09124148357522649),
 (715, 0.09078412990032037),
 (1142, 0.09078412990032037),
 (1306, 0.09078412990032037),
 (2562, 0.09078412990032037),
 (3537, 0.09078412990032037),
 (389, 0.09078412990032035),
 (11, 0.09058216273156766),
 (129, 0.09058216273156766),
 (243, 0.09058216273156766),
 (473, 0.09058216273156766),
 (600, 0.09058216273156766),
 (933, 0.09058216273156766),
 (997, 0.09058216273156766),
 (2556, 0.09058216273156766),
 (486, 0.09038153754011029),
 (2570, 0.09007912422186248),
 (266, 0.08968970586617499),
 (412, 0.08968970586617499),
 (1692, 0.08968970586617499),
 (1783, 0.08968970586617499),
 (1906, 0.08968970586617499),
 (2243, 0.08968970586617499),
 (2592, 0.08968970586617499),
 (239, 0.08951435925492911),
 (12, 0.08920515501750789),
 (167, 0.08920515501750789),
 (219, 0.08920515501750789),
 (980, 0.08920515501750789),
 (1408, 0.08920515501750789),
 (1480, 0.08920515501750789),
 (3322, 0.08920515501750789),
 (4671, 0.08920515501750789),
 (297, 0.0888231183368655),
 (752, 0.0888231183368655),
 (1278, 0.0888231183368655),
 (2856, 0.0888231183368655),
 (2880, 0.0888231183368655),
 (3462, 0.0888231183368655),
 (4097, 0.0888231183368655),
 (4502, 0.0888231183368655),
 (169, 0.08798117404291673),
 (596, 0.08798117404291673),
 (1019, 0.08798117404291673),
 (1233, 0.08798117404291673),
 (1357, 0.08798117404291673),
 (35, 0.08770580193070292),
 (88, 0.08770580193070292),
 (141, 0.08770580193070292),
 (292, 0.08770580193070292),
 (341, 0.08770580193070292),
 (511, 0.08770580193070292),
 (564, 0.08770580193070292),
 (1027, 0.08770580193070292),
 (1756, 0.08770580193070292),
 (2651, 0.08770580193070292),
 (2660, 0.08770580193070292),
 (2957, 0.08770580193070292),
 (199, 0.08716272672808179),
 (331, 0.08716272672808179),
 (1832, 0.08716272672808179),
 (2363, 0.08716272672808179),
 (4343, 0.08716272672808179),
 (304, 0.08699848552934203),
 (143, 0.0863667034175061),
 (746, 0.0863667034175061),
 (2109, 0.0863667034175061),
 (23, 0.08627959628145762),
 (356, 0.08627959628145762),
 (775, 0.08627959628145762),
 (1474, 0.08627959628145762),
 (2093, 0.08627959628145762),
 (2251, 0.08627959628145762),
 (2538, 0.08627959628145762),
 (3449, 0.08627959628145762),
 (4657, 0.08627959628145762),
 (827, 0.08559209850218259),
 (1276, 0.08559209850218259),
 (1530, 0.08559209850218259),
 (2388, 0.08559209850218259),
 (3553, 0.08559209850218259),
 (4516, 0.08559209850218259),
 (4587, 0.08559209850218259),
 (59, 0.08534859274986485),
 (2, 0.08492077756084468),
 (1097, 0.08492077756084468),
 (1249, 0.08492077756084468),
 (1259, 0.08492077756084468),
 (2840, 0.08492077756084468),
 (3195, 0.08492077756084468),
 (3448, 0.08492077756084468),
 (2740, 0.08483796839677037),
 (2448, 0.08439494725697222),
 (32, 0.084103426706236),
 (234, 0.084103426706236),
 (270, 0.084103426706236),
 (618, 0.084103426706236),
 (2003, 0.084103426706236),
 (2596, 0.084103426706236),
 (1, 0.08362420100070908),
 (646, 0.08362420100070908),
 (691, 0.08362420100070908),
 (960, 0.08362420100070908),
 (1269, 0.08362420100070908),
 (1473, 0.08362420100070908),
 (1589, 0.08362420100070908),
 (2295, 0.08362420100070908),
 (2304, 0.08362420100070908),
 (2683, 0.08362420100070908),
 (2794, 0.08362420100070908),
 (4259, 0.08362420100070908),
 (2115, 0.08347257041177224),
 (19, 0.08338763984501665),
 (602, 0.08338763984501665),
 (1305, 0.08338763984501665),
 (274, 0.08308641921035717),
 (479, 0.08302258023111965),
 (62, 0.0826898230594723),
 (381, 0.0826898230594723),
 (1698, 0.0826898230594723),
 (2796, 0.0826898230594723),
 (3154, 0.0826898230594723),
 (3556, 0.0826898230594723),
 (3978, 0.0826898230594723),
 (4737, 0.0826898230594723),
 (2386, 0.08257978997938135),
 (39, 0.08238525545716345),
 (315, 0.08238525545716345),
 (626, 0.08238525545716345),
 (745, 0.08238525545716345),
 (894, 0.08238525545716345),
 (3764, 0.08238525545716345),
 (4560, 0.08238525545716345),
 (2354, 0.08200923681047297),
 (1202, 0.08134518347820842),
 (2968, 0.08134518347820842),
 (242, 0.081199794294115),
 (245, 0.081199794294115),
 (1688, 0.081199794294115),
 (1700, 0.081199794294115),
 (1749, 0.081199794294115),
 (2661, 0.081199794294115),
 (222, 0.0806970043558403),
 (501, 0.0806970043558403),
 (193, 0.08006407690254358),
 (63, 0.08006407690254357),
 (121, 0.08006407690254357),
 (203, 0.08006407690254357),
 (457, 0.08006407690254357),
 (534, 0.08006407690254357),
 (547, 0.08006407690254357),
 (866, 0.08006407690254357),
 (987, 0.08006407690254357),
 (1139, 0.08006407690254357),
 (2128, 0.08006407690254357),
 (2167, 0.08006407690254357),
 (2219, 0.08006407690254357),
 (2339, 0.08006407690254357),
 (3140, 0.08006407690254357),
 (3180, 0.08006407690254357),
 (3527, 0.08006407690254357),
 (3728, 0.08006407690254357),
 (4641, 0.08006407690254357),
 (4718, 0.08006407690254357),
 (4754, 0.08006407690254357),
 (107, 0.07944581222989573),
 (190, 0.07944581222989573),
 (217, 0.07944581222989573),
 (1898, 0.07944581222989573),
 (2203, 0.07944581222989573),
 (2792, 0.07944581222989573),
 (37, 0.07897471897389846),
 (71, 0.07897471897389846),
 (152, 0.07897471897389846),
 (164, 0.07897471897389846),
 (227, 0.07897471897389846),
 (530, 0.07897471897389846),
 (899, 0.07897471897389846),
 (901, 0.07897471897389846),
 (1080, 0.07897471897389846),
 (1207, 0.07897471897389846),
 (1289, 0.07897471897389846),
 (1790, 0.07897471897389846),
 (3028, 0.07897471897389846),
 (3135, 0.07897471897389846),
 (3301, 0.07897471897389846),
 (3816, 0.07897471897389846),
 (4341, 0.07897471897389846),
 (38, 0.07884165279854434),
 (103, 0.0782510703046739),
 (812, 0.0782510703046739),
 (1534, 0.0782510703046739),
 (101, 0.07792865001991967),
 (329, 0.07792865001991967),
 (361, 0.07792865001991967),
 (787, 0.07792865001991967),
 (3926, 0.07792865001991967),
 (4316, 0.07792865001991967),
 (4640, 0.07792865001991967),
 (584, 0.07767356373806174),
 (1664, 0.07767356373806174),
 (2165, 0.07767356373806174),
 (2877, 0.07767356373806174),
 (4473, 0.07767356373806174),
 (4492, 0.07767356373806174),
 (4542, 0.07767356373806174),
 (4654, 0.07767356373806174),
 (2005, 0.07710865759549869),
 (349, 0.07692307692307693),
 (508, 0.07692307692307693),
 (922, 0.07692307692307693),
 (1113, 0.07692307692307693),
 (1290, 0.07692307692307693),
 (1623, 0.07692307692307693),
 (153, 0.07655590023509527),
 (286, 0.07655590023509527),
 (1828, 0.07655590023509527),
 (4181, 0.07655590023509527),
 (785, 0.07601486235852867),
 (1659, 0.07601486235852867),
 (96, 0.075955452531275),
 (98, 0.075955452531275),
 (210, 0.075955452531275),
 (1519, 0.075955452531275),
 (2865, 0.075955452531275),
 (3470, 0.075955452531275),
 (4624, 0.075955452531275),
 (51, 0.07548513560963972),
 (800, 0.07548513560963972),
 (850, 0.07548513560963972),
 (1254, 0.07548513560963972),
 (1282, 0.07548513560963972),
 (2274, 0.07548513560963972),
 (2712, 0.07548513560963972),
 (3126, 0.07548513560963972),
 (3430, 0.07548513560963972),
 (3560, 0.07548513560963972),
 (3832, 0.07548513560963972),
 (4000, 0.07548513560963972),
 (4279, 0.07548513560963972),
 (4506, 0.07548513560963972),
 (40, 0.07502344849205331),
 (235, 0.07502344849205331),
 (241, 0.07502344849205331),
 (1161, 0.07502344849205331),
 (1293, 0.07502344849205331),
 (2644, 0.07502344849205331),
 (3164, 0.07502344849205331),
 (4055, 0.07502344849205331),
 (4268, 0.07502344849205331),
 (246, 0.07496633127898335),
 (1924, 0.07496633127898335),
 (3905, 0.07496633127898335),
 (4305, 0.07496633127898335),
 (125, 0.07457013045372174),
 (16, 0.07412493166611012),
 (503, 0.07412493166611012),
 (557, 0.07412493166611012),

In [47]:
recommend('Man of Steel')

Superman Returns
X-Men: First Class
Batman v Superman: Dawn of Justice
Superman II
Ong Bak 2

In [42]:
import pickle

In [43]:
pickle.dump(new_df.to_dict(), open('model/movie_dict.pkl', 'wb'))

In [45]:
new_df.to_csv('movies_new.csv', index=False, encoding='utf-8')

In [94]:
import pickle
import pandas as pd
import requests
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def fetch_posters(movie_id):
    response = requests.get(f'https://api.themoviedb.org/3/movie/{movie_id}?api_key=a8ceee02bc23cd72797db38f57aa42c1&language=en-US')
    data = response.json()
    return "https://image.tmdb.org/t/p/w500" + data['poster_path']


def recommendations(movies_list):
    # movies_list = ['Superman Returns', 'Spider-Man 3']
    tag = movies_df[movies_df['title'].isin(movies_list)].tags.str.cat(sep=' ')
    q = pd.DataFrame({"title": "shubh","tags":tag},index=[5000])
    df1 = pd.concat([movies_df, q])
    vectors = cv.fit_transform(df1['tags']).toarray()
    cv.get_feature_names_out()
    similarity = cosine_similarity(vectors)
    distances = similarity[-1]
    movies_output = sorted(list(enumerate(distances)), reverse=True, key=lambda x: x[1])[1:(9+len(movies_list))]
    recommended_movies = []
    for i in movies_output:
        tmp = movies_df.iloc[i[0]]
        if tmp.title not in movies_list:
            path = fetch_posters(tmp.movie_id)
            recommended_movies.append({"title":tmp.title, "path": path})
    return recommended_movies



movies_dict = pickle.load(open('model/movie_dict.pkl', 'rb'))
movies_df = pd.DataFrame(movies_dict)
cv = CountVectorizer(max_features=5000, stop_words='english')

recommendations(['Superman Returns', 'The Dark Knight'])

[{'title': 'Batman Begins',
  'path': 'https://image.tmdb.org/t/p/w500/4MpN4kIEqUjW8OPtOQJXlTdHiJV.jpg'},
 {'title': 'Batman',
  'path': 'https://image.tmdb.org/t/p/w500/zzoPxWHnPa0eyfkMLgwbNvdEcVF.jpg'},
 {'title': 'Superman',
  'path': 'https://image.tmdb.org/t/p/w500/d7px1FQxW4tngdACVRsCSaZq0Xl.jpg'},
 {'title': 'Superman II',
  'path': 'https://image.tmdb.org/t/p/w500/jw0tYFCbzjBN8SIhvRC2kdh7pzh.jpg'},
 {'title': 'Batman',
  'path': 'https://image.tmdb.org/t/p/w500/cij4dd21v2Rk2YtUQbV5kW69WB2.jpg'},
 {'title': 'The Dark Knight Rises',
  'path': 'https://image.tmdb.org/t/p/w500/85cWkCVftiVs0BVey6pxX8uNmLt.jpg'},
 {'title': 'Batman Returns',
  'path': 'https://image.tmdb.org/t/p/w500/jKBjeXM7iBBV9UkUcOXx3m7FSHY.jpg'},
 {'title': 'Superman IV: The Quest for Peace',
  'path': 'https://image.tmdb.org/t/p/w500/vhs3P0JwqzlgfBqhjnCWDEOtDmS.jpg'}]